language: java
sudo: false
jdk:
  - oraclejdk8
install: true

branches:
  only:
  - master
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - mvn clean install cobertura:cobertura
  
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT